### ISSUE TITLE
Version 7.0.* errors transpiling JSX in files

### ISSUE THREAD

**Issue by phillipCouto** [babel/babelify#127] opened 2015-10-30 20:09 UTC
When I run bablify in gulp using the latest version which at the time of writing is 7.0.2 I get the following error:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

SyntaxError: /tmp/eSpace/js/src/espace.js: Unexpected token (14:15)
  12 | node = document.getElementById('preferencesManager');
  13 | if (node) {
> 14 |   React.render(<PreferencesManager/>, node);
     |                ^
  15 | }
  16 | 
  17 | node = document.getElementById('groupsManager');
    at Parser.pp.raise (/tmp/eSpace/js/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/tmp/eSpace/js/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:91:8)
    at Parser.pp.parseExprAtom (/tmp/eSpace/js/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:486:12)
    at Parser.pp.parseExprSubscripts (/tmp/eSpace/js/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:244:19)
    at Parser.pp.parseMaybeUnary (/tmp/eSpace/js/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:225:19)
    at Parser.pp.parseExprOps (/tmp/eSpace/js/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:171:19)
    at Parser.pp.parseMaybeConditional (/tmp/eSpace/js/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:153:19)
    at Parser.pp.parseMaybeAssign (/tmp/eSpace/js/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:120:19)
    at Parser.pp.parseExprListItem (/tmp/eSpace/js/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:945:16)
    at Parser.pp.parseCallExpressionArguments (/tmp/eSpace/js/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:315:20)

```
If I change the version of babelify to "6.*" in the package.json and run gulp again it completes successfully.

**Comment by jmm** [comment] 2015-10-30 20:17
Duplicate of #126.

**Closed** 2015-10-31 22:49 UTC
